### ISSUE TITLE
manual_run error in version 2021.3.29

### ISSUE THREAD

**Issue by miguelpucela** [rgc99/irrigation_unlimited#3]
First of all, thank for your work. It is great and I'm enjoying it a lot and find it very useful.

Calling to manual_run doesn't work in last version (2021.3.29) while run smothly in previous ones.

Content of the error in log file (lots of errors exactly like this): 

```
2021-03-31 10:39:24 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/irrigation_unlimited/irrigation_unlimited.py", line 1620, in _async_timer
    self.poll(time)
  File "/config/custom_components/irrigation_unlimited/irrigation_unlimited.py", line 1556, in poll
    if self.muster(wtime, force) != 0:
  File "/config/custom_components/irrigation_unlimited/irrigation_unlimited.py", line 1532, in muster
    status |= controller.muster(time, force)
  File "/config/custom_components/irrigation_unlimited/irrigation_unlimited.py", line 1327, in muster
    zone_status |= zone.muster(time, zone.schedules, None, None, force)
  File "/config/custom_components/irrigation_unlimited/irrigation_unlimited.py", line 938, in muster
    status |= self._run_queue.merge(
  File "/config/custom_components/irrigation_unlimited/irrigation_unlimited.py", line 695, in merge
    run = self.find_last_by_id(schedule.id)
  File "/config/custom_components/irrigation_unlimited/irrigation_unlimited.py", line 541, in find_last_by_id
    if run.parent.id == id:
AttributeError: 'NoneType' object has no attribute 'id'
```

I'm runing Home Assistant 2021.3.4 with core-2021.3.4 if that's relevant.

My contiguration is this:

```
granularity: 10
controllers:
  - name: 'Riego pueblo'
    enabled: true
    zones:
     - name: 'Zona 1'
       enabled: true
       minimum: '00:00'
       maximum: '00:10'
       entity_id: 'switch.sonoff_1000caee3e_1'
       schedules:
         - name: 'Primavera'
           time:
              sun: 'sunrise'
              after: '00:00'
           duration: '00:08'
           month: [mar, apr, may]
     - name: 'Zona 2'
... (similar to previous).
```

Thank you.
--

**Comment by rgc99** [comment]
Thanks for the error log. It helped me zero in and nail the issue. Will get an update out shortly.

**Comment by miguelpucela** [comment]
With the last update, `manual_run` works again smoothly.

Thank you for the quick update.
